### ISSUE TITLE
Can't build after adding plugin.

### ISSUE THREAD

**Issue by jcassidyav** [nativescript-community/licenses#1]
after I've added this to my project with ```ns plugin add @nativescript-community/licenses```

I now get the following when I do ```ns build android```

```Error: spawn ./gradlew ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)```

Is there anything I can do to see what the issue is?

**Comment by farfromrefug** [comment]
@jcassidyav you need to give more of the log. can't say just with that

**Comment by jcassidyav** [comment]
sorry missed a line 

```Webpack compilation complete.
Error: spawn ./gradlew ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

The rest of the log is just as normal

So does this plugin work on windows?  when  I change the line in the plugin that spawns gradlew to 

```
                var command = child_process_1.spawn('gradlew.bat', ['generateLicenseReport', '--rerun-tasks'], {
                    cwd: path.join(projectData.projectDir, 'platforms/android'),
                    env: Object.assign(process.env, {
                        LICENSES_OUTPUT_PATH: process.env.LICENSES_OUTPUT_PATH || projectFilesPath
                    }, { shell: true })

``` 
I start to see output from the plugin, culminating in 

a file named null being created in the platforms\android\app\src\main\assets\app with a list of dependencies.


When I set the env variable LICENSES_FILE_NAME then the file gets the name set to this.

**Comment by farfromrefug** [comment]
@jcassidyav shoot i did not handle windows :s
I ll do that!  and fix the license filename!
THnaks

**Comment by farfromrefug** [comment]
@jcassidyav should be fixed in 1.1.8

**Comment by jcassidyav** [comment]
That's great thanks so much!

so I do have a general question, when I look at the generated File I do not see entries for any of the Nativescript plugins I added to my project, for example this plugin.  Is that expected? if so any recommendations on how to gather those ?

**Comment by farfromrefug** [comment]
@jcassidyav yes for now that plugin only handle native libs. Shoud be possible though

**Comment by jcassidyav** [comment]
1.1.8 allows me to build on windows, thanks for releasing so quickly.

I am however still seeing a null filename.

changing: dependency-report.gradle

```
def licensesFileName = "$System.env.LICENSES_FILE_NAME" 
if (pathToLicenses == "") {
  pathToLicenses = "licenses.json"
}
```

to 

```
def licensesFileName = "$System.env.LICENSES_FILE_NAME" 
if (licensesFileName == "null") {
  licensesFileName = "licenses.json"
}
```

fixes it for me.

**Comment by farfromrefug** [comment]
@jcassidyav i see my  bad thanks for the report and fix!

**Comment by jcassidyav** [comment]
I think you missed the bit that it changed the variable name being set from pathToLicenses  to licensesFileName .

licensesFileName  is still not set.

**Comment by farfromrefug** [comment]
@jcassidyav i try to do too many things at the same time :s i am really sorry!

**Comment by jcassidyav** [comment]
> @jcassidyav i try to do too many things at the same time :s i am really sorry!

No problem thanks for all your efforts, I should really have looked at raising a pull request.

**Comment by jcassidyav** [comment]
1.1.10 working for me now with filename etc. thanks.
